# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
environment: dev
autoscaler:
  enabled: false
disruptionbudget:
  enabled: false
ingress:
  # Used to create an Ingress record.
  records:
    - host: api.dev.ovid-project.com
resources:
   limits:
    cpu: 1000m
    memory: 1500Mi
   requests:
    cpu: 100m
    memory: 512Mi
endpoints:
  ticketget: https://masmovil-test-staging.apigee.net/masmovil/v1
config:
  keysPrefix: ticketing
  redis:
    host: redis
    port: 6379
    database: 11
  salesforce:
    tokenUrl: https://masmovil--devtkt01.cs100.my.salesforce.com/services/oauth2
    apiUrl: https://masmovil--dev01.cs86.my.salesforce.com
    apiVersion: services/data/v44.0
    ticketUrl: https://masmovil--devtkt01.cs86.my.salesforce.com/    